DEFINE
    VAR _ServiceGroupFilter =
        TREATAS(
            {
                "Microsoft.Azure.HybridData.AdxProxy",
                "Microsoft.Azure.HybridData.Alerts",
                "Microsoft.Azure.HybridData.AppTelemetry.CoreInfra",
                "Microsoft.Azure.HybridData.ARNIngestion",
                "Microsoft.Azure.HybridData.ControlPlane",
                "Microsoft.Azure.HybridData.HaaS",
                "Microsoft.Azure.HybridData.ImageReplication",
                "Microsoft.Azure.HybridData.InventoryManagement",
                "Microsoft.Azure.HybridData.LoadTest",
                "Microsoft.Azure.HybridData.MigrationServices",
                "Microsoft.Azure.HybridData.MirrorMaker",
                "Microsoft.Azure.HybridData.Onboarding",
                "Microsoft.Azure.HybridData.OneMonitoring.TelemetryCollector",
                "Microsoft.Azure.HybridData.RegionalCore",
                "Microsoft.Azure.HybridData.RegionalCore.AppTelemetry.ClusterInternal",
                "Microsoft.Azure.HybridData.ReleaseOperationsTest",
                "Microsoft.Azure.HybridData.ResourceProvider",
                "Microsoft.Azure.HybridData.Runners",
                "Microsoft.Azure.HybridData.SecOps.Release",
                "Microsoft.Azure.HybridData.SharedDataServices",
                "Microsoft.Azure.HybridData.SqlOpsMcpService",
                "Microsoft.Azure.HybridData.SqlVmLicensingStorage",
                "Microsoft.Azure.HybridData.TelemetryIntelligence.AppTelemetryExternal",
                "Microsoft.Azure.HybridData.TelemetryIntelligence.ArcEnabledServer",
                "Microsoft.Azure.HybridData.TelemetryIntelligence.DefenderForSQL",
                "Microsoft.Azure.HybridData.TelemetryIntelligence.Scrapy",
                "Microsoft.Azure.HybridData.TelemetryIntelligence.StreamProcessing",
                "Microsoft.Azure.HybridData.UsageProcessing"
            },
            'Service Group'[service_group]
        )
    VAR _NonBlankDateFilter =
        FILTER(
            ALL('Date'[date]),
            NOT ISBLANK('Date'[date])
        )

EVALUATE
    SUMMARIZECOLUMNS(
        'Date'[date],
        _ServiceGroupFilter,
        _NonBlankDateFilter,
        "Rollout Attempts", [Rollout Attempts],
        "Successful Rollouts", [Successful Rollouts],
        "Failed Rollouts", [Failed Rollouts],
        "Rollout Success Rate", [Rollout Success Rate]
    )
ORDER BY
    'Date'[date] ASC
